services:
  mongo:
    image: mongo
    container_name: distribuidos_db
    ports:
      - "27017:27017"
    volumes:
      - ./Almacenamiento:/data/db
      - ./data_host:/datos

  redis:
    image: redis:latest
    container_name: distribuidos_redis
    ports:
      - "6379:6379"

  scrapper:
    build:
      context: ./Scrapper
      dockerfile: Dockerfile
    container_name: Scrapper
    depends_on:
      - mongo
    working_dir: /app
    volumes:
      - ./Scrapper:/app
    stdin_open: true
    tty: true

  cache:
    build:
      context: ./Cache
      dockerfile: Dockerfile
    container_name: cache
    depends_on:
      - mongo
      - redis
    ports:
      - "8000:8000"
    working_dir: /Cache
    volumes:
      - ./Cache:/Cache
    stdin_open: true
    tty: true

  generador_de_trafico:
    build:
      context: ./Generador_de_Trafico
      dockerfile: Dockerfile
    container_name: generador_de_trafico
    depends_on:
      - cache
    working_dir: /Generador_de_Trafico
    volumes:
      - ./Generador_de_Trafico:/Generador_de_Trafico
    stdin_open: true
    tty: true

  hadoop:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: distribuidos_hadoop
    environment:
      - CLUSTER_NAME=demo-cluster
      - CORE_CONF_fs_defaultFS=hdfs://hadoop:9000
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - hadoopnet

  hadoop-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: distribuidos_datanode
    environment:
      - CLUSTER_NAME=demo-cluster
      - CORE_CONF_fs_defaultFS=hdfs://hadoop:9000
      - HDFS_CONF_dfs_replication=1
    ports:
      - "9864:9864"
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    networks:
      - hadoopnet

  pig:
    image: fluddeni/hadoop-pig
    container_name: distribuidos_pig
    depends_on:
      - hadoop
      - hadoop-datanode
    stdin_open: true
    tty: true
    networks:
      - hadoopnet
    volumes:
      - ./pig:/pig
      - ./hadoop-conf:/etc/hadoop/conf:ro
    working_dir: /pig
    environment:
      HADOOP_CONF_DIR: /etc/hadoop/conf
    command: ["bash"]

volumes:
  hadoop_namenode:
  hadoop_datanode:

networks:
  hadoopnet: