services:
    mongo:
        image: mongo
        container_name: distribuidos_db
        ports:
            -  "27017:27017"
        volumes:
            -  ./Almacenamiento:/data/db
    redis:
        image: redis:latest
        container_name: distribuidos_redis
        ports:
            - "6379:6379"
    scrapper:
        build:
            context: ./Scrapper
            dockerfile: Dockerfile
        container_name: Scrapper
        depends_on:
            -  mongo
        working_dir: /app
        volumes:
            -  ./Scrapper:/app
        stdin_open: true
        tty: true
    cache:
        build:
            context: ./Cache
            dockerfile: Dockerfile
        container_name: cache
        depends_on:
            -  mongo
            -  redis
        ports:
            -  "8000:8000"
        working_dir: /Cache
        volumes:
            -  ./Cache:/Cache
        stdin_open: true
        tty: true
    generador_de_trafico:
        build:
            context: ./Generador_de_Trafico
            dockerfile: Dockerfile
        container_name: generador_de_trafico
        depends_on:
            -  cache
        working_dir: /Generador_de_Trafico
        volumes:
            -  ./Generador_de_Trafico:/Generador_de_Trafico
        stdin_open: true
        tty: true